// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKXHFRNJNU7a29H5JdiSkMPHVqTo8ZeC0',
    appId: '1:60811045152:web:5a8acb05e31f0c1979cf45',
    messagingSenderId: '60811045152',
    projectId: 'eventorg-513da',
    authDomain: 'eventorg-513da.firebaseapp.com',
    storageBucket: 'eventorg-513da.appspot.com',
    measurementId: 'G-K4BLXZ80YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_Dm7ObQ29M_j4Wj7b9VQXuEs6-HoXrU',
    appId: '1:60811045152:android:aadc779b5b1f650b79cf45',
    messagingSenderId: '60811045152',
    projectId: 'eventorg-513da',
    storageBucket: 'eventorg-513da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_sran8fp3hGcee6MK-eOu30vrEoSKFE',
    appId: '1:60811045152:ios:80ba2a39fed9588479cf45',
    messagingSenderId: '60811045152',
    projectId: 'eventorg-513da',
    storageBucket: 'eventorg-513da.appspot.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_sran8fp3hGcee6MK-eOu30vrEoSKFE',
    appId: '1:60811045152:ios:80ba2a39fed9588479cf45',
    messagingSenderId: '60811045152',
    projectId: 'eventorg-513da',
    storageBucket: 'eventorg-513da.appspot.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKXHFRNJNU7a29H5JdiSkMPHVqTo8ZeC0',
    appId: '1:60811045152:web:0c2f2cffccc04e0379cf45',
    messagingSenderId: '60811045152',
    projectId: 'eventorg-513da',
    authDomain: 'eventorg-513da.firebaseapp.com',
    storageBucket: 'eventorg-513da.appspot.com',
    measurementId: 'G-8SR3NWED7B',
  );
}
